### ISSUE TITLE
Existential operator explanation confusing and/or incorrect?

### ISSUE THREAD

**Issue by jmoe** [autotelicum/Smooth-CoffeeScript#1]
On pages 38/39 where the existential operator is first mentioned, a sentence reads :

"It returns true, if something is null or undefined."

But my quick tests seem to indicate that the opposite is true. It returns true of something is _not_ null or undefined.

For example, from the coffee interpreter :

coffee> test?
false
coffee> test = null
null
coffee> test?
false
coffee> test = undefined
coffee> test?
false
coffee> test = 'test'
test
coffee> test?
true

**Comment by autotelicum** [comment]
It is an error on p 41 top / 39 top. It should have been the same as in the reference on page 218 / 201.

The description of the existential operator should be: 'It returns true unless something is null or undefined.'

It is difficult to proofread my own text, so do let me know if you find anything else. Thank you for reporting it.

**Comment by jmoe** [comment]
Yup, cool! I'm reading the whole thing, so I'll report anything else that is confusing. Awesome so far, thanks!
