### ISSUE TITLE
Translation for Korean

### ISSUE THREAD

**Issue by leedaeyeop** [autotelicum/Smooth-CoffeeScript#15]
Hi, autotelicum!
I'm Dae-yeop Lee and I work for WIKIBOOKS, a publishing company in South Korea.

http://www.wikibook.co.kr

WIKIBOOKS has been established since Mar. 2006 and specialized in Computer & Information Technology Books.
I have known that you have published good book and I think it will be very popular between Korean readers.
And then, I am interested in translating into Korean Language for your book.

So, Could you let me know if it is available?
If it is available, I'd like to contact with you.

Best regards,
Dae-yeop

**Comment by autotelicum** [comment]
You are welcome to translate it to Korean. Just keep in mind that you have to abide by the license. I can't change it as the book is a derivate work. If you need clarification on some text or example then you can post any questions here.

The interactive (in gh-pages) and the print editions (in the main branch) differ mainly in referring to the browser versus the node server environment. They also use different tools/file formats: LyX for print, pandoc markdown for HTML5.

**Comment by autotelicum** [comment]
As mentioned all source code is available on github in the two branches. I am not sure what else you would need from me, so I am closing this issue.

**Comment by leedaeyeop** [comment]
Oh, thank you for your reply.
All I want was final PDF(with solutions) file, and I got it from the repository.
I will start translation as soon as possible, and inform you when I publish the book. 
Thanks again for your great work. :)
