### ISSUE TITLE
Show globals in REPL

### ISSUE THREAD

**Issue by autotelicum** [autotelicum/Smooth-CoffeeScript#2]
In the book it is described that definitions created in the REPL can be seen by typing:
`this.` followed by `TAB`
That worked in 1.1.1 but not in 1.1.2. A workaround is to define:

``` coffeescript
gdef = -> g for g of global
```

Executing it gives a list of definitions:

``` coffeescript
gdef()
```

[Edit: fixed in coffeescript development - to be included in the next version]

**Comment by michaelficarra** [comment]
`Object.getOwnPropertyNames this`

**Comment by autotelicum** [comment]
Handled by update to CoffeeScript 1.1.3
