### ISSUE TITLE
`Basic CoffeeScript` issues

### ISSUE THREAD

**Issue by aeosynth** [autotelicum/Smooth-CoffeeScript#4]
page 21:

> As you might have guessed, the multiplication happens first

you might want to mention PEMDAS for the people who couldn't guess. this is an introductory text after all, some readers might not have a solid math background.

> The first example shows that multiplication has a higher precedence than addition.

the first example doesn't show anything - we're told what happens in the explanation.

> Division and multiplication always come before subtraction and addition

that's just PEMDAS again. why not add another sentence saying "parenthesis always comes before exponentiating always comes before (division and multiplication) always come before (subtraction and addition)". explain the concept fully once and then move on.

22:

> small snippets of CoffeeScript code between _#{_ and }

are the characters `#{` _italicized_?

25:

```
true and false
```

a lot of these examples would benefit with a comment displaying the result:

```
true and false # false
```

> You can reduce it step by step like this:

if you really want to go step by step, there's one step you skipped:

```
true and true
```

**Comment by autotelicum** [comment]
I am adding this to the end of the Foreword:

'''
To get the most out of the book: Start your text editor and in src-no-solutions open the source code file for the chapter you are reading. If you have a wide-screen display then arrange your windows so the book is on one side and the text editor on the other. Then you can read and run the samples, see the results, experiment with the code and solve the exercises.

If you make copies of the files you work on then you can easily undo experiments. If you get stuck with an exercise then copy my solution from the file in the src directory and study it a bit before moving on. Note that in some of the source files you have to indent your solutions to match the surrounding code.
'''

I think that should solve the main issue you raise here. Why not insert the output in the book? It would take days to do it throughout the book and add something like 50 pages. Some output can not be inserted, it runs a server and/or a browser. In my view a developer should execute the scripts in his/her own editor and experiment with the code.

Italicized? Yes, the syntax highlighter sees that as a comment. An example without the formatting issue is shown just below. I'm not going to change that, nor insert `true and true`. There are a few other details - like incorrect highlighting of a few words - that I am aware of but they do not make the text incomprehensible or incorrect.

The conversational style and the silly/funny/thought provoking examples are important parts of the book. Explain it once and move on is a different writing style. To see what I am talking about, skip into the paradigm part and read the book on programming within this book on programming.

**Comment by autotelicum** [comment]
Revised foreword included in 3rd revision.
