### ISSUE TITLE
Cannot use prelude

### ISSUE THREAD

**Issue by IgorGanapolsky** [autotelicum/Smooth-CoffeeScript#5]
Hello,
when I am in the src directory and run the command "coffee -r prelude 00-Foreword.coffee", I get an error:

module.js:317
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'prelude'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at /usr/local/lib/node/.npm/coffee-script/1.0.0/package/lib/command.js:105:9
    at /usr/local/lib/node/.npm/coffee-script/1.0.0/package/lib/command.js:83:26
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12)
    at wrapper (fs.js:245:17)

Any ideas?

Thank you,
Igor

**Comment by autotelicum** [comment]
The source files load the prelude (in the first statement) so you don't have to do it on the command line e.g.
    coffee 00-Foreword.coffee
To make the module system look for a module in the current directory you could write:
    coffee -r ./prelude 00-Foreword.coffee
The `coffee -r ./prelude` is only needed for an interactive interpreter (REPL) with definitions preloaded.

**Comment by michaelsbradleyjr** [comment]
I'm tying to make use of your `prelude` bundle in conjunction with the `coffee` REPL. While in `~/experiments/Smooth-CoffeeScript/src` if I run:

```
coffee -r ./prelude
```

Something doesn't seem to working correctly:

```
coffee> show 'something'
ReferenceError: show is not defined
  at [object Context]:2:5
  at Object.eval (/home/michael/.nvm/v0.4.11/lib/node_modules/coffee-script/lib/coffee-script.js:114:21)
  at Interface.<anonymous> (/home/michael/.nvm/v0.4.11/lib/node_modules/coffee-script/lib/repl.js:44:34)
  at Interface.emit (events.js:64:17)
  at Interface._onLine (readline.js:153:10)
  at Interface._line (readline.js:408:8)
  at Interface._ttyWrite (readline.js:585:14)
  at ReadStream.<anonymous> (readline.js:73:12)
  at ReadStream.emit (events.js:81:20)
  at ReadStream._emitKey (tty_posix.js:307:10)
```

Am I doing something wrong?

I'm running node v0.4.11 with the latest stable npm and a fresh npm global-install of `coffee-script`.

**Comment by autotelicum** [comment]
Immediately it looks like a change introduced in CoffeeScript 1.1.12 affecting global objects. I'll investigate it more - I have not found any documentation yet, only the changelog mentions: "a REPL overhaul".

**Comment by michaelsbradleyjr** [comment]
Okay, great, thanks for your quick reply.

**Comment by autotelicum** [comment]
Adding definitions to the global namespace seems to be disabled for modules in the CoffeeScript 1.1.12 REPL, so the -r command line option does not add the definitions, neither does it work to require the prelude from inside the REPL.

It does not affect files that are executed and require the prelude, so the code samples can still be run with `coffee filename`.

A workaround is to add this to the end of the `prelude/prelude.coffee` file:

``` coffeescript
exports.prelude = prelude
```

and then start the REPL with `coffee` and execute this:

``` coffeescript
{prelude} = require './prelude'
global[name] = prelude[name] for name of prelude
```

The last is needed because the `prelude.globalize` function can not be used in the 1.1.12 REPL.

This seems to be related to changes made for CoffeeScript Issue #1035. Which has been closed, so I'll construct a minimal sample (tomorrow) and raise a new issue.

**Comment by michaelsbradleyjr** [comment]
Thanks, that's a mostly painless work-around which allows me to proceed with my tinkering in the REPL viz-a-viz the `prelude` facilities.

One thing I did notice is that I'm getting "double output" from the `show` function:

```
... steps completed per your previous comment ...
coffee> show 'text'
text
'text'
```

**Comment by autotelicum** [comment]
It is because `show` returns the value it displays and that value is then displayed by the REPL.
It is usually not needed to use `show` in the REPL, simply typing a variable name will display its value.
In a file you have to use `show` or another output function to see the result of something.
Sometimes `show` can be handy in the REPL, this is a non-sensical example but:

``` coffeescript
f = (x) -> x*2
[Function]
# The REPL only shows the type of for example functions
coffee> f
[Function]
# show gives more detail here the translated definition of the function in JavaScript
coffee> show f
function (x) {
  return x * 2;
}
[Function]

# When you have some code that does not do exactly what you expect...
coffee> x = if 2 > 3 then f f 2 else f f 3
12

# then because show returns its value you can call it in the middle of an expression:
coffee> x = if 2 > 3 then f show f 2 else f show f 3
6
12
```

**Comment by autotelicum** [comment]
Opened Issue #1654 in the CoffeeScript project regarding using globals in modules and the REPL (i.e. using the prelude and globalize). Will see if it is known, intentional or a mishap.

**Comment by michaelsbradleyjr** [comment]
Thanks for the explanation of the "double output" -- that's very handy actually as it's an easy way to study the results of coffeescript's source->source compilation.

I'll be monitoring issue #1654 too and appreciate your diligence in investigating this matter.

**Comment by michaelsbradleyjr** [comment]
CoffeeScript's [issue #1654](https://github.com/jashkenas/coffee-script/issues/1654) has been closed, as of tonight.

It looks like the case we made eventually won out, especially in light of node's REPL having been changed in v0.5.10 to support the visibility of state changes in `global` (e.g. by a `require`d module) within the REPL context.

**Comment by autotelicum** [comment]
Thanks for your assistance and perseverance in resolving this issue.

Next step is [node.js 0.6](http://blog.nodejs.org/2011/10/25/version-0-6/), hopefully soon after followed by an updated CoffeeScript. It will take me some time after that to retest/rewrite/update everything for a 3rd revision. Changes include native Windows node.js, CoffeeKup 0.3.1 and an update of WebSocket to ensure compatibility with the latest browser versions.

**Comment by autotelicum** [comment]
Handled by update to CoffeeScript 1.1.3
